version: '3'

services:
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - 8000:80
      - 4443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

  gitlab:
    image: gitlab/gitlab-ce:latest
    restart: always
    ports:
      - 22:22
      - 8001:80
      - 4444:443
    volumes:
      - gitlab_data:/var/opt/gitlab
      - gitlab_logs:/var/log/gitlab
      - gitlab_config:/etc/gitlab

networks:
  default:
    internal: true

volumes:
  gitlab_data:
  gitlab_logs:
  gitlab_config:
